import * as stylex from '@stylexjs/stylex';
import { colors, radius } from '../../styles/tokens.stylex';

export const styles = stylex.create({
   wrapper: {
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
      marginTop: '16px',
   },
   topLabel: {
      fontSize: '1.125rem',
      fontWeight: '500',
      color: colors.textPrimary,
   },
   container: {
      display: 'flex',
      gap: '8px',
   },
   trigger: {
      position: 'relative',
      flex: '1',
      width: '100%',
      height: '56px',
      paddingTop: '18px',
      paddingBottom: '6px',
      paddingLeft: '12px',
      paddingRight: '8px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      fontSize: '16px',
      color: colors.textPrimary,
      backgroundColor: colors.bgSecondary,
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: colors.border,
      borderRadius: radius.lg,
      cursor: 'pointer',
      transition: 'border-color 0.15s ease',
      ':hover': {
         borderColor: colors.accent,
      },
   },
   triggerLabel: {
      position: 'absolute',
      left: '12px',
      top: '50%',
      transform: 'translateY(-50%)',
      fontSize: '16px',
      fontWeight: '400',
      color: colors.textSecondary,
      pointerEvents: 'none',
      transition: 'top 0.15s ease, font-size 0.15s ease, transform 0.15s ease',
   },
   triggerLabelFloated: {
      top: '6px',
      transform: 'translateY(0)',
      fontSize: '12px',
   },
   content: {
      backgroundColor: colors.bgElevated,
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: colors.border,
      borderRadius: radius.md,
      padding: '1px',
      maxHeight: '200px',
      overflowY: 'auto',
      zIndex: 50,
      minWidth: 'var(--radix-dropdown-menu-trigger-width)',
   },
   item: {
      padding: '12px',
      fontSize: '16px',
      color: colors.textPrimary,
      borderRadius: radius.sm,
      cursor: 'pointer',
      outline: 'none',
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
});
