import * as stylex from '@stylexjs/stylex';
import { colors, radius, spacing } from '../../styles/tokens.stylex';

export const styles = stylex.create({
   content: {
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: 'min(450px, 94dvw)',
      backgroundColor: colors.bgBubble,
      borderRadius: radius.xl,
      overflow: 'hidden',
      zIndex: 51,
      display: 'flex',
      flexDirection: 'column',
      '@media (max-width: 480px)': {
         width: '100vw',
         top: 'auto',
         left: 0,
         bottom: 0,
         transform: 'none',
         borderBottomLeftRadius: 0,
         borderBottomRightRadius: 0,
      },
   },
   header: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: `${spacing.md} ${spacing.md}`,
      borderBottom: `1px solid ${colors.separator}`,
   },
   title: {
      fontSize: '1rem',
      fontWeight: 600,
      color: colors.textPrimary,
   },
   closeButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: colors.textPrimary,
      padding: spacing.xs,
      borderRadius: radius.full,
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
   shareButton: {
      padding: '16px',
      fontSize: '0.875rem',
      fontWeight: 700,
      color: colors.accent,
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
      ':disabled': {
         color: colors.textMuted,
         cursor: 'default',
      },
   },
   body: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: spacing.lg,
      gap: spacing.md,
      minHeight: '280px',
      position: 'relative',
   },
   textarea: {
      width: '100%',
      background: 'transparent',
      border: 'none',
      outline: 'none',
      resize: 'none',
      fontSize: '1rem',
      color: colors.textPrimary,
      textAlign: 'center',
      lineHeight: 1.5,
      minHeight: '60px',
   },
   avatarWrapper: {
      width: '120px',
      height: '120px',
      borderRadius: radius.full,
      overflow: 'hidden',
      flexShrink: 0,
      backgroundColor: colors.buttonHover,
   },
   avatarPlaceholder: {
      width: '120px',
      height: '120px',
      borderRadius: radius.full,
      backgroundColor: colors.buttonHover,
      flexShrink: 0,
   },
   emojiButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: colors.textSecondary,
      fontSize: '1.4rem',
      padding: spacing.xs,
      borderRadius: radius.full,
      ':hover': {
         color: colors.textPrimary,
         backgroundColor: colors.buttonHover,
      },
   },
   emojiPickerWrapper: {
      position: 'absolute',
      bottom: '60px',
      left: '50%',
      transform: 'translateX(-50%)',
      zIndex: 10,
   },
   charCount: {
      fontSize: '0.75rem',
      color: colors.textMuted,
      alignSelf: 'flex-end',
   },
   charCountWarning: {
      color: colors.danger,
   },
   footer: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      padding: `${spacing.sm} ${spacing.md}`,
      borderTop: `1px solid ${colors.separator}`,
      cursor: 'pointer',
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
   footerText: {
      fontSize: '0.85rem',
      color: colors.textPrimary,
      fontWeight: 500,
   },
   footerIcon: {
      color: colors.textSecondary,
      fontSize: '1rem',
   },
   footerChevron: {
      color: colors.textSecondary,
      fontSize: '0.75rem',
      marginLeft: 'auto',
   },
   deleteButton: {
      padding: '16px',
      fontSize: '0.875rem',
      fontWeight: 700,
      color: colors.danger,
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
      ':disabled': {
         opacity: 0.5,
         cursor: 'default',
      },
   },
   separator: {
      height: '1px',
      backgroundColor: colors.elevatedSeparator,
   },
});
