import * as stylex from '@stylexjs/stylex';
import { colors, radius } from '../../styles/tokens.stylex';

export const styles = stylex.create({
   overlay: {
      position: 'fixed',
      inset: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      zIndex: 19,
   },
   content: {
      position: 'fixed',
      top: 0,
      left: 0,
      bottom: 0,
      width: '460px',
      display: 'flex',
      flexDirection: 'column',
      padding: '16px',
      backgroundColor: colors.bg,
      borderRightStyle: 'solid',
      borderRightColor: colors.separator,
      borderRightWidth: 1,
      zIndex: 20,
      outline: 'none',
   },
   header: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '24px 24px 16px',
   },
   title: {
      fontSize: '24px',
      fontWeight: 700,
      color: colors.textPrimary,
   },
   closeButton: {
      position: 'absolute',
      top: '4px',
      right: '4px',
      padding: '8px',
      borderRadius: radius.full,
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
   filterButton: {
      fontSize: '14px',
      fontWeight: 600,
      color: colors.accentText,
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      padding: '4px 8px',
      borderRadius: radius.sm,
      ':hover': {
         color: colors.accentTextHover,
      },
   },

   chipsRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      paddingTop: '8px',
      paddingLeft: '24px',
      overflowX: 'auto',
   },
   chip: {
      fontSize: '12px',
      fontWeight: 600,
      color: colors.textPrimary,
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: colors.border,
      borderRadius: radius.xxl,
      padding: '8px 16px',
      cursor: 'pointer',
      whiteSpace: 'nowrap',
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
   chipActive: {
      backgroundColor: colors.bgBubble,
      borderStyle: 'none',
      ':hover': {
         backgroundColor: colors.textPrimary,
      },
   },
   chipIcon: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '36px',
      height: '36px',
      borderRadius: radius.full,
      backgroundColor: colors.bgSecondary,
      color: colors.textPrimary,
      border: 'none',
      cursor: 'pointer',
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },

   filterPanel: {
      position: 'absolute',
      top: '80px',
      right: '16px',
      width: '320px',
      backgroundColor: colors.bgElevated,
      borderRadius: radius.lg,
      padding: '16px',
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
      boxShadow: '0 4px 24px rgba(0,0,0,0.3)',
      zIndex: 30,
   },
   filterSectionTitle: {
      fontSize: '14px',
      fontWeight: 600,
      color: colors.textSecondary,
      padding: '8px 0',
   },
   filterOption: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      fontSize: '14px',
      color: colors.textPrimary,
      padding: '10px 8px',
      borderRadius: radius.sm,
      cursor: 'pointer',
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
   filterCheckbox: {
      width: '18px',
      height: '18px',
      accentColor: colors.accent,
      cursor: 'pointer',
   },
   filterDivider: {
      height: '1px',
      backgroundColor: colors.separator,
      margin: '8px 0',
   },
   applyButton: {
      marginTop: '12px',
      width: '100%',
      padding: '12px',
      fontSize: '14px',
      fontWeight: 600,
      color: colors.textPrimary,
      backgroundColor: colors.primaryButton,
      border: 'none',
      borderRadius: radius.lg,
      cursor: 'pointer',
      ':hover': {
         opacity: 0.9,
      },
   },

   list: {
      flex: 1,
      overflowY: 'auto',
      paddingTop: '8px',
   },
   groupHeader: {
      fontSize: '16px',
      fontWeight: 700,
      color: colors.textPrimary,
      padding: '0px 24px 8px',
   },
   notificationItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      padding: '10px 24px',
      cursor: 'pointer',
      ':hover': {
         backgroundColor: colors.threadHover,
      },
   },
   notificationAvatarWrapper: {
      position: 'relative',
      flexShrink: 0,
   },
   notificationAvatar: {
      borderRadius: '50%',
      objectFit: 'cover',
   },
   secondaryAvatar: {
      position: 'absolute',
      bottom: '-2px',
      right: '-2px',
      width: '22px',
      height: '22px',
      borderRadius: '50%',
      border: `2px solid ${colors.bg}`,
      overflow: 'hidden',
   },
   notificationBody: {
      flex: 1,
      minWidth: 0,
   },
   notificationText: {
      fontSize: '14px',
      lineHeight: '18px',
      color: colors.textPrimary,
      wordWrap: 'break-word',
   },
   timeAgo: {
      fontSize: '14px',
      color: colors.textSecondary,
      marginLeft: '6px',
      whiteSpace: 'nowrap',
   },
   targetThumbnail: {
      borderRadius: radius.sm,
      objectFit: 'cover',
      flexShrink: 0,
   },
   followButton: {
      fontSize: '14px',
      fontWeight: 600,
      color: colors.textPrimary,
      backgroundColor: colors.primaryButton,
      border: 'none',
      borderRadius: radius.lg,
      padding: '7px 16px',
      cursor: 'pointer',
      flexShrink: 0,
      ':hover': {
         opacity: 0.9,
      },
   },
   emptyState: {
      padding: '48px 24px',
      textAlign: 'center',
      fontSize: '14px',
      color: colors.textSecondary,
   },
});
