import * as stylex from '@stylexjs/stylex';
import { colors, radius } from '../../../../../../styles/tokens.stylex';

export const styles = stylex.create({
   root: {
      position: 'absolute',
      bottom: '0',
      left: '0',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '12px 16px',
      gap: '16px',
      borderTopWidth: '1px',
   },
   leftControls: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
   },
   controlWrapper: {
      position: 'relative',
   },
   controlButton: {
      width: '36px',
      height: '36px',
      borderRadius: radius.full,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      color: 'white',
      border: 'none',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      ':hover': {
         backgroundColor: 'rgba(0, 0, 0, 0.8)',
      },
   },
   ratioMenu: {
      position: 'absolute',
      bottom: 'calc(100% + 8px)',
      left: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      borderRadius: radius.md,
      padding: '8px 0',
      minWidth: '140px',
      backdropFilter: 'blur(10px)',
   },
   ratioMenuItem: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '8px 16px',
      background: 'none',
      border: 'none',
      color: colors.textSecondary,
      fontSize: '14px',
      width: '100%',
      ':hover': {
         backgroundColor: 'rgba(255, 255, 255, 0.1)',
      },
   },
   ratioMenuItemActive: {
      color: colors.textPrimary,
   },
   ratioIcon: {
      width: '16px',
      borderWidth: '1.5px',
      borderStyle: 'solid',
      borderColor: 'currentColor',
      borderRadius: '2px',
   },
   zoomPopup: {
      position: 'absolute',
      bottom: 'calc(100% + 8px)',
      left: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      borderRadius: radius.md,
      padding: '12px 16px',
      minWidth: '160px',
      backdropFilter: 'blur(10px)',
   },
   zoomSlider: {
      width: '100%',
   },
   popoverContent: {
      backgroundColor: colors.bgElevated,
      borderRadius: radius.lg,
      padding: '12px',
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
      zIndex: 100,
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: colors.border,
   },
   popoverThumbnails: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
   },
   popoverScroll: {
      display: 'flex',
      gap: '8px',
      overflowX: 'auto',
      scrollbarWidth: 'none',
      '::-webkit-scrollbar': {
         display: 'none',
      },
      maxWidth: '360px',
   },
   popoverThumbWrapper: {
      position: 'relative',
      flexShrink: 0,
      cursor: 'grab',
   },
   popoverThumbWrapperDragOver: {
      opacity: 0.5,
      cursor: 'grabbing',
   },
   popoverThumb: {
      position: 'relative',
      width: '80px',
      height: '80px',
      borderRadius: radius.sm,
      overflow: 'hidden',
      flexShrink: 0,
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: 'none',
      padding: 0,
      ':hover': {
         borderColor: colors.border,
      },
   },
   popoverThumbActive: {
      borderColor: colors.accentText,
   },
   popoverAddButton: {
      width: '80px',
      height: '80px',
      borderRadius: radius.sm,
      borderWidth: '2px',
      borderStyle: 'dashed',
      borderColor: colors.border,
      backgroundColor: colors.bgSecondary,
      color: colors.textSecondary,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      ':hover': {
         borderColor: colors.textSecondary,
         color: colors.textPrimary,
      },
   },
   popoverArrow: {
      background: 'none',
      border: 'none',
      padding: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
   },
   thumbImage: {
      objectFit: 'cover',
   },
   thumbRemove: {
      position: 'absolute',
      top: '4px',
      right: '4px',
      width: '18px',
      height: '18px',
      borderRadius: radius.full,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      color: 'white',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
      ':hover': {
         backgroundColor: 'rgba(0, 0, 0, 0.9)',
      },
   },
});
