import * as stylex from '@stylexjs/stylex';
import { colors, radius } from '../../../../styles/tokens.stylex';

export const styles = stylex.create({
   root: {
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
   },
   header: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '4px 16px',
      borderBottomWidth: '1px',
      borderBottomStyle: 'solid',
      borderBottomColor: colors.border,
      backgroundColor: colors.bg,
      flexShrink: 0,
   },
   headerButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '8px',
      background: 'none',
      border: 'none',
      borderRadius: radius.full,
      color: colors.textPrimary,
      ':hover': {
         backgroundColor: colors.buttonHover,
      },
   },
   headerTitle: {
      fontSize: '16px',
      fontWeight: 700,
      color: colors.textPrimary,
   },
   shareButton: {
      padding: '8px 0',
      background: 'none',
      border: 'none',
      color: colors.accentText,
      fontSize: '14px',
      fontWeight: 600,
      ':hover': {
         color: colors.accentTextHover,
      },
   },
   body: {
      display: 'flex',
      flex: 1,
      overflow: 'hidden',
      position: 'relative',
   },
   previewSection: {
      flex: 1,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      backgroundColor: colors.bgSecondary,
      overflow: 'hidden',
      userSelect: 'none',
      width: '700px',
   },
   cropContainer: {
      position: 'relative',
      overflow: 'hidden',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'crosshair',
   },
   cropContainerVideo: {
      cursor: 'default',
   },
   previewImage: {
      flexShrink: 0,
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      userSelect: 'none',
      pointerEvents: 'none',
   },
   arrowLeft: {
      position: 'absolute',
      left: '12px',
      top: '50%',
      transform: 'translateY(-50%)',
      zIndex: 2,
   },
   arrowRight: {
      position: 'absolute',
      right: '12px',
      top: '50%',
      transform: 'translateY(-50%)',
      zIndex: 2,
   },
   tagHint: {
      position: 'absolute',
      top: '12px',
      left: '50%',
      transform: 'translateX(-50%)',
      backgroundColor: 'rgba(0,0,0,0.75)',
      color: 'white',
      borderRadius: radius.lg,
      padding: '6px 14px',
      fontSize: '13px',
      fontWeight: 500,
      pointerEvents: 'none',
      whiteSpace: 'nowrap',
      zIndex: 3,
   },
   tagPopper: {
      position: 'absolute',
      zIndex: 100,
      backgroundColor: colors.bgBubble,
      borderRadius: radius.md,
      overflow: 'hidden',
      width: '260px',
      boxShadow: '0 4px 20px rgba(0,0,0,0.4)',
   },
});
