import * as stylex from '@stylexjs/stylex';
import { colors, radius, spacing } from '../../../../../../styles/tokens.stylex';

export const styles = stylex.create({
   root: {
      position: 'relative',
      maxWidth: 630,
   },
   storiesRow: {
      display: 'flex',
      flexDirection: 'row',
      gap: '18px',
      overflowX: 'auto',
      paddingBottom: spacing.xs,
      borderBottom: `1px solid ${colors.separator}`,
      paddingTop: '8px',
      paddingLeft: '12px',
      position: 'relative',
      scrollbarWidth: 'none',
   },
   storiesRowButton: {
      display: 'flex',
      padding: '8px',
      borderRadius: radius.full,
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      zIndex: 1,
      transition: 'visibility 0s',
      ':hover': {
         backgroundColor: 'rgba(255, 255, 255, 0.3)',
      },
      ':disabled': {
         color: colors.textPrimary,
      },
   },
   storiesRowButtonLeft: {
      left: '0',
   },
   storiesRowButtonRight: {
      right: '0',
   },
   hidden: {
      visibility: 'hidden',
      pointerEvents: 'none',
   },
   navIcon: {
      fontSize: 24,
   },
   navIconLeft: {
      transform: 'rotate(90deg)',
   },
   navIconRight: {
      transform: 'rotate(-90deg)',
   },
   storyLink: {
      display: 'contents',
   },
   storyItem: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '6px',
      cursor: 'pointer',
      flexShrink: 0,
   },
   storyRing: {
      padding: '3px',
      borderRadius: radius.full,
      backgroundImage: 'linear-gradient(45deg, #f09433, #bc1888)',
   },
   storyRingInner: {
      padding: '3px',
      borderRadius: radius.full,
      backgroundColor: colors.bg,
   },
   storyAvatar: {
      borderRadius: radius.full,
   },
   storyUsername: {
      fontSize: '0.7rem',
      color: colors.textPrimary,
      maxWidth: '64px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      textAlign: 'center',
   },
   addStoryCard: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      position: 'relative',
      gap: '6px',
      flexShrink: 0,
   },
   addStoryRingWrapper: {
      position: 'relative',
      width: '86px',
      height: '86px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
   },
   addStoryAvatar: {
      borderRadius: '50%',
      objectFit: 'cover',
   },
   addStoryPlusBadge: {
      position: 'absolute',
      bottom: 16,
      right: 0,
      width: '28px',
      height: '28px',
      borderRadius: '50%',
      backgroundColor: colors.whiteBlack,
      color: colors.blackWhite,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '18px',
      fontWeight: 700,
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: colors.bgBubble,
   },
   storyRingViewed: {
      backgroundImage: 'none',
      backgroundColor: colors.buttonHover,
   },
   noteStoryItem: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '6px',
      cursor: 'pointer',
      flexShrink: 0,
      position: 'relative',
   },
   noteBubble: {
      position: 'absolute',
      top: '0',
      left: '50%',
      transform: 'translateX(-50%)',
      backgroundColor: 'rgba(0,0,0,0.82)',
      borderRadius: '14px',
      padding: '5px 10px',
      fontSize: '0.72rem',
      color: '#fff',
      whiteSpace: 'nowrap',
      maxWidth: '96px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      zIndex: 1,
      pointerEvents: 'none',
   },
   noteBubbleInner: {},
   noteStoryWrapper: {
      position: 'relative',
      paddingTop: '30px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '6px',
      flexShrink: 0,
   },
   addNoteLabel: {
      fontSize: '0.7rem',
      color: colors.textPrimary,
      maxWidth: '64px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      textAlign: 'center',
   },
});
